// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQKD-Lf-91hNKgY8mR5p6yCg7g1ph9eQ',
    appId: '1:1057937195563:web:14c29181650295abb7206e',
    messagingSenderId: '1057937195563',
    projectId: 'flutter-login-project-9564c',
    authDomain: 'flutter-login-project-9564c.firebaseapp.com',
    storageBucket: 'flutter-login-project-9564c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk__f_2HnM3Ww-hCqsxf8cR5yevmYRnOY',
    appId: '1:1057937195563:android:edba03cb78858272b7206e',
    messagingSenderId: '1057937195563',
    projectId: 'flutter-login-project-9564c',
    storageBucket: 'flutter-login-project-9564c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN6BkqKRmS038uI-yxgEwDYgx9ChjFsmk',
    appId: '1:1057937195563:ios:9ddef23f5de77639b7206e',
    messagingSenderId: '1057937195563',
    projectId: 'flutter-login-project-9564c',
    storageBucket: 'flutter-login-project-9564c.appspot.com',
    iosBundleId: 'com.example.fullApp',
  );
}
